#!/usr/bin/env bash

targetDir=docs

# shellcheck disable=SC2115
rm -r $targetDir/*

function buildLocale() {
    lang=$1
    targetLocaleDir=$targetDir/$lang
    mkdir -p "$targetLocaleDir"
    node_modules/mustache/bin/mustache locale/"$lang".json src/index.mustache > "$targetLocaleDir"/index.html
}
buildLocale pl
buildLocale en

cp static/* $targetDir
cp CNAME $targetDir
cp robots.txt $targetDir
